### PR TITLE
lecture 7 notes

### PR DESCRIPTION
**Pull request by wolmsted**
Ben Barnett did RANSAC,
Trevor Danielson did Local Invariant Features,
Kelsey Wang did Keypoint Localization,
Wesley Olmsted did Scale Invariant Keypoint Detection.

### CODE REVIEW

**Comment by omoindrot** [comment]
Hi, thanks for your lecture notes.
Could you add the compiled pdf to the folder?

Thanks a lot.

**Comment by wolmsted** [comment]
Just added it. Sorry, I didn't realize it was in the gitignore.

**Comment by omoindrot** [comment]
Thanks, could you add captions for every figure with a short explanation + source of the image?

**Comment by wolmsted** [comment]
If I got it from the slides, how would I cite it?

**Comment by omoindrot** [comment]
You can see how other students did it in previous lecture notes.

**Comment by wolmsted** [comment]
Ok so is a short comment with the description and source underneath the figure is fine? No need to use bibtex?

**Comment by omoindrot** [comment]
If the figure comes from a paper you need to cite it using bibtex.

**Comment by wolmsted** [comment]
@omoindrot added the descriptions and sources

**Comment by omoindrot** [comment]
Thank you for the work on the lecture notes, I'll merge.

**Pull request merged**
