### PR TITLE
add lecture6 notes

### PR DESCRIPTION
**Pull request by hesamh22**
lecture6 notes

### CODE REVIEW

**Comment by omoindrot** [comment]
Thanks for the lecture notes !
Could you add the compiled pdf in the repository?

Also could you detail the work repartition in a comment here?

**Comment by hesamh22** [comment]
I added the pdf file. 
Edge detection: Winston Wang (wwang13@cs.stanford.edu)
Hough: Antonio Tan-Torres (tantonio@cs.stanford.edu)
RANSAC: Hesam Hamledari (hesamh@stanford.edu)

**Comment by omoindrot** [comment]
Thanks. Some comments from the teaching team:
- [x] add more information in the introduction about why we are covering these topics. Why are they relevant to computer vision in general?
- [x] remove bullet points in section 2.2 (Edge basics) and add full sentences + example images of the different types of edges
- [ ] section 2.3.1, the gradient should be df/dx at value x
  - [ ] forward way is in the wrong order, should be `f(x+1) - f(x)`
  - [ ] central way is divided by 2
- [x] figures 7, 8, 9 don't appear?

Please correct them and add it to the pull request !

**Comment by hesamh22** [comment]
Thanks for the feedback. 
The Fig. 7, 8, 9 do appear in the uploaded PDF. 
I will look into them.

**Comment by hesamh22** [comment]
All errors were corrected. 
I've triple checked to make sure all figures do appear. 
Please let me know if I should revise anything. 

Thanks 
-Hesam

**Comment by hesamh22** [comment]
Hi CS131 team, 
Please note that my last commit (ae1edf1...) is for the **Lecture04** where:
- I corrected a few errors
- revised the style and grammar of text (e.g., removed typos, fixed sentences etc.)
- this commit has nothing to do with "lecture06" which we were assigned to prepare notes for.

Thanks 
-Hesam Hamledari

**Comment by hesamh22** [comment]
I also revised the .tex (and PDF) files for **Lecture03**; please see the following commits (bcc28a0) and (30b6069)
- corrected a few typos
- revised the text in terms of grammar, clarity, etc.
- (again, this has nothing to do with my lecture06 assignment/commits)
Thanks
-Hesam Hamledari

**Comment by hesamh22** [comment]
Revisions/corrections for **Lecture02** >> commit (b93a574) 
-Hesam

**Comment by omoindrot** [comment]
Thank you @UbermenschIsHere for all your modifications + contributions to the previous lecture notes.

**Pull request merged**
