### PR TITLE
Lecture 13 notes

### PR DESCRIPTION
**Pull request by jrcabansag**
My SUID is cabansag, and I wrote everything between Figure 8 and the end of the LDA with 2 variables section

### CODE REVIEW

**Comment by gpreud** [comment]
gpreud: Overleaf + Git Setup, Eigenfaces section, Eigenface vs Fisherface Results subsection of LDA

**Comment by omoindrot** [comment]
Great notes ! I don't see anything missing, just don't store `.DS_Store` in the GitHub repo next time :)

**Comment by dunchadhn** [comment]
My SUID is dunlyons and I wrote the Introduction Section.

**Comment by jgriffi2** [comment]
jgriffi2: Proofreading, checking for accurate information, and a little bit of the LDA section.

**Comment by yuxingch** [comment]
yxchen28: LDA with N Variables and C Classes, Results: Eigenface vs. Fisherface, and bibliography.

**Pull request merged**
