### PR TITLE
lecture 2 notes

### PR DESCRIPTION
**Pull request by CoolNamesAllTaken**
second time's the charm?

### CODE REVIEW

**Comment by omoindrot** [comment]
Great work, just a few things to fix before I can merge:
- can you remove the bullet points and form full sentences?
- remove `format.tex` from the pull request
- make sure all the images you use have proper source (figure 2 doesn't have a caption)

Thanks.

**Comment by CoolNamesAllTaken** [comment]
Made the first two fixes, but waiting on a collaborator to fix the figure captions

**Comment by omoindrot** [comment]
Thanks, I'll merge and grade the notes.
Also please add a comment here about how the work was split up between members of your team.

**Comment by CoolNamesAllTaken** [comment]
jmcnelly: Physics of Color, overleaf + git setup, work distribution
haighal: White Balancing
msaviano: Linear Algebra
scottkaz: Color Space
camvdg: Human Encoding of Color

**Pull request merged**
