### PR TITLE
Added Lecture 9

### PR DESCRIPTION
**Pull request by rachel-1**
Mason Swofford, Rachel Gardner, Yue Zhang, Shawn Fenerin

### CODE REVIEW

**Comment by omoindrot** [comment]
Could you detail who did what in the notes?

Some feedback to improve the notes before I can merge:

- [ ] add legends to every figure, with the source of the image
- [ ] in 2.3, you say the cost is `O(smn)` but what is `s`?
- [ ] in 2.4, please have a better formatting for the algorithm in latex
- [ ] in 2.4, average energy of the image will **increase** as we remove the low energy seams. The whole paragraph after that needs to be clarified
- [ ] in 3.4, "there is the less noticeable limitation", "that important to the image". Clarify the whole paragraph
- [ ] in 3.5, "lowest energy pictures", "our previous method can considered", "source ???"

Overall try to have a more *scientific* language and add more sources.

Thanks !

**Comment by rachel-1** [comment]
We have the names in the comments of the .tex file, but here is the breakdown:

Section 1 - Yue
Section 2.1 to 2.3 - Yue 
Section 2.4 - Gustavo
Section 3.1 to 3.3 - Rachel
Section 3.4 to 3.6 -Shawn
Section 4 - Mason

People are making changes to their respective sections. I'll commit changes when they finish.

**Comment by rachel-1** [comment]
I've updated the pull request with the new changes. By the way, is there any particular format you want image sources to be in? For example, we cited several figures that appeared in lecture slides (but didn't have citations when they appeared in lecture). I looked at some other groups, but they just referenced slide numbers (which is what we ended up doing).

**Comment by omoindrot** [comment]
That's fine, thank you for the work !

**Pull request merged**
