### PR TITLE
Lecture 11 notes

### PR DESCRIPTION
**Pull request by cgo2**
Kevin Culberg - Mean-Shift section
Caitlin Go - Object Recognition; K-Nearest Neighbors - supervised learning, nearest neighbors classifier, k nearest neighbors
Darrith Phan and Zahra Abdullah - K-Nearest Neighbors - pros, issues, generalization, bias/ variance tradeoff

### CODE REVIEW

**Comment by omoindrot** [comment]
Thanks ! Some comments:

- [ ] in 1.1, remove the bullet points
- [ ] same in 3.4

**Comment by omoindrot** [comment]
@cgo2 : can you correct the two small points above and push to your repo?

**Comment by cgo2** [comment]
Added requested changes! Sorry for the delay

**Comment by omoindrot** [comment]
Thanks !

**Pull request merged**
