### PR TITLE
Lecture 14 notes

### PR DESCRIPTION
**Pull request by ShubhangDesai**
Notes for lecture on Bag of Words

### CODE REVIEW

**Comment by meghabyte** [comment]
meghas: overleaf setup, introduction: ideas + origin
jtaylor5: intro para, large scale image search
shubhang: outline, git setup
samprem: naive bayes
zwang141: pyramids

**Comment by omoindrot** [comment]
Thanks @meghabyte @ShubhangDesai .
Some notes to correct before I can merge:
- [ ] last sentence in section 1 has no end?
- [ ] title "2. Bag of Words Outline" seems weird. Do you want to use the word "outline"?
- [ ] describe more what the results are in section 3.4
- [ ] overall some typos, could be good to proofread

**Comment by omoindrot** [comment]
@ShubhangDesai @meghabyte any update on this?

**Comment by ShubhangDesai** [comment]
@omoindrot sorry for the delay. We're currently working on it and expect to get it done this weekend.

**Comment by ShubhangDesai** [comment]
@omoindrot sorry again for the delay. made edits and just pushed the changes!

**Comment by omoindrot** [comment]
Ok thanks

**Comment by omoindrot** [comment]
@ShubhangDesai: you actually removed the pdf, can you add it again (in a different pull request?)

**Comment by ShubhangDesai** [comment]
@omoindrot sorry, I just saw this! I see that you've added the PDF to the main repo, appreciate it.

**Pull request merged**
