### PR TITLE
Add Lecture 05 Notes

### PR DESCRIPTION
**Pull request by shivaalroy**

### CODE REVIEW

**Comment by omoindrot** [comment]
Could you add the pdf in the folder please?
Also can you provide the repartition of contributions in comments?

**Comment by shivaalroy** [comment]
The .gitignore has *.pdf. Do you want me to --force add it? What do you mean by repartition of contributions?

**Comment by omoindrot** [comment]
Yes please !
I've removed the `*.pdf` from the gitignore file, so you can pull recent changes and then add the pdf without forcing.

**Comment by omoindrot** [comment]
@shivaalroy ?

**Comment by shivaalroy** [comment]
Sorry, I forgot to add the PDF. It should be added now!

**Comment by omoindrot** [comment]
- [x] The latex in section 1.3 is not outputting correctly?
- [x] Same in section 3.3
- [ ] You need to use a proper bibliography for your sources, and not just say "Source: L. Fei-fei" for instance

**Comment by shivaalroy** [comment]
Ok the issues with section 1.3 and 3.3 are fixed. We didn't have the sources for the images since they were from the lecture slides, so we took out the images.

**Comment by omoindrot** [comment]
Don't remove any of the images, but you can cite the lecture slides of CS131 (check other lecture notes to see how they did).

Also please update the pdf when you update the tex.

**Comment by shivaalroy** [comment]
Ok, we added the images back in and cited them as other lecture notes did.

**Comment by omoindrot** [comment]
Great thanks for the work.

**Pull request merged**
